---
- name: downloading the package java
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64.tar.gz
    headers: "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"
    dest: /usr/local/src/
    validate_certs: no

- name: extracting contents
  command: tar -xf /usr/local/src/jdk-8u181-linux-x64.tar.gz -C /opt/

- name: installing stuff
  command: "alternatives --install /usr/bin/java java /opt/jdk1.8.0_181/bin/java 2"
  args:
      chdir: /opt/jdk1.8.0_181
...    
